const IMAGES = {
	LOAD: 'IMAGES_LOAD',
	LOAD_SUCCESS: 'IMAGES_SUCCESS',
	LOAD_FAIL: 'IMAGES_FAIL',
};

const STATS = {
	LOAD: 'STATS_LOAD',
	LOAD_SUCCESS: 'STATS_SUCCESS',
	LOAD_FAIL: 'STATS_FAIL',
};

export { IMAGES, STATS };
